"""исправилене моделей users и cart - насторйка удаления cascad

Revision ID: 49bb76c98c2e
Revises: 4b0b2bed10ae
Create Date: 2025-12-28 17:52:03.668157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bb76c98c2e'
down_revision: Union[str, Sequence[str], None] = '4b0b2bed10ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
