"""добавил каскадное удаление для моделей: Token, Cart

Revision ID: 4b0b2bed10ae
Revises: 6e1a7e014479
Create Date: 2025-12-27 05:09:01.528727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0b2bed10ae'
down_revision: Union[str, Sequence[str], None] = '6e1a7e014479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.drop_constraint(op.f('cart_product_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('token_user_id_fkey'), 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key(op.f('token_user_id_fkey'), 'token', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_product_id_fkey'), 'cart', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
