"""добавил поле login для таблицы user

Revision ID: 5545665b1519
Revises: 49bb76c98c2e
Create Date: 2026-01-18 04:05:53.320615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5545665b1519'
down_revision: Union[str, Sequence[str], None] = '49bb76c98c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
