"""empty message

Revision ID: 6e1a7e014479
Revises: 
Create Date: 2025-12-25 17:27:42.161673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1a7e014479'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'gallery', 'products', ['product_id'], ['id'])
    op.add_column('users', sa.Column('account_status', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_status')
    op.drop_constraint(None, 'gallery', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    # ### end Alembic commands ###
